/*
 * This source file was generated by the Gradle 'init' task
 */
package competec;

import java.util.Scanner;

public class App2 {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var sc = new Scanner(System.in);
        System.out.println(new App().getGreeting());
    }
}
